name: WebdriverIO Tests

on:
  push:
    branches: [ automation_web ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      # - name: Install Allure Commandline
      #   run: npm install -g allure-commandline

      # - name: Generate Allure Report
      #   run: allure generate allure-results --clean -o allure-report

      # Optional: Upload report as artifact (for download/view)
      # - name: Upload Allure Report as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: allure-report
      #     path: allure-report
