name: WebdriverIO Tests

on:
  push:
    branches: [ automation_web ]
  pull_request:
    branches: [ automation_web ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()  # agar tetap dijalankan meski test gagal
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results --clean -o allure-report
          else
            echo "No allure-results found. Skipping report generation."
          fi

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
