name: WebdriverIO Tests

on:
  push:
    branches: [ automation_web ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Setup xvfb and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg

      - name: Run WDIO Tests with xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          DISPLAY=:99 npm run testNGenerate

      - name: List generated files for debugging
        run: |
          echo "=== VIDEOS ==="
          ls -l videos || echo "No videos"
          echo "=== CUSTOM HTML ==="
          ls -l custom-html/attachments || echo "No attachments"
          echo "=== ALLURE ==="
          ls -l allure-results || echo "No allure results"

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Ensure output folders exist
        run: |
          mkdir -p videos
          mkdir -p custom-html/attachments

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Custom HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: custom-html
          path: custom-html

      - name: Upload Video Recordings
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: videos
